INSERT INTO GENEROS(NOMBRE) VALUES('Accion');
INSERT INTO GENEROS(NOMBRE) VALUES('Comedia');
INSERT INTO GENEROS(NOMBRE) VALUES('Drama');
INSERT INTO GENEROS(NOMBRE) VALUES('Fantasia');
INSERT INTO GENEROS(NOMBRE) VALUES('Terror');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Hailee Steinfeld', 'https://m.media-amazon.com/images/I/616qV6830xL._AC_SX679_.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Elizabeth Olsen', 'https://media.vogue.mx/photos/5f622891bf6d0f39b17f33ac/1:1/w_2025,h_2025,c_limit/la-actriz-elizabeth-olsen.jpg');
INSERT INTO ACTORES(NOMBRE, URL_IMAGEN) VALUES('Isabela Merced', 'https://i.pinimg.com/236x/67/ed/a0/67eda08c7173a3910799499ce968751a.jpg');

INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Transformers 5', 1, '2027-06-20');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Los Vengadores: La Batalla Final', 1, '2026-05-04');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Rápidos y Furiosos 11', 1, '2028-08-10');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('La Gran Estafa', 2, '2025-12-15');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El Detective Aficionado', 2, '2024-11-10');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('La Oficina del Caos', 2, '2029-07-19');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Corazón Valiente', 3, '2023-03-03');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El Camino de la Vida', 3, '2026-10-22');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Amor en Tiempos Modernos', 3, '2025-02-14');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El Reino Encantado', 4, '2028-11-11');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El Hechizo de la Luna', 4, '2024-04-05');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('La Espada de Fuego', 4, '2025-06-30');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Noche de Sustos', 5, '2027-10-31');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El Fantasma de la Opera', 5, '2029-02-20');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('La Maldición de la Casa', 5, '2026-09-15');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Guardianes de la Galaxia 4', 1, '2028-04-28');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Agentes Secretos 3', 1, '2026-07-18');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('La Comedia de los Errores', 2, '2025-05-12');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('Sonrisas de Verano', 2, '2023-06-22');
INSERT INTO PELICULAS(NOMBRE, GENERO_ID, FECHA_ESTRENO) VALUES ('El Misterio de la Rosa', 3, '2027-01-08');


